Manipulator:
  name: abv_dxl

MobileBase:
  name: abv # omit this whole key (or leave name blank/null) for a standalone manipulator

StateMachine:
  rate: 25 # Hz

Engine:
  rate: 50 # Hz

  Planning:
    type: simple

  GraspPlanning:
    type: pca
    visualize: false
