Manipulator:
  name: dxl

Robot:
  name: abv
  manip_attach_link: vehicle_link

StateMachine:
  rate: 25 # Hz

Engine:
  rate: 50 # Hz

  Planning:
    type: simple

  GraspPlanning:
    type: pca
    visualize: false
