name: ubuntu-22.04

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ROS_META_PKG: ros-humble-ros-base
      WS: robot_ws

    steps:
      - name: setup workspace
        run: |
          set -eux 
          mkdir -p ${{ env.WS }}/src

      - name: Checkout A.R.M repo
        uses: actions/checkout@v4
        with:
          path: src/arm
          submodules: "recursive"

      - name: clone dep repos
        working-directory: ${{ env.WS }}/src
        run: |
          set -eux
          pwd
          git clone https://github.com/samlovelace/robot_idl.git
          ls

      - name: run setup scripts
        working-directory: ${{ env.WS }}/src/robot_idl/scripts
        run: |
          set -eux
          chmod +x ./setup.sh
          ./setup.sh manipulation

      - name: Build with colcon (Release)
        working-directory: ${{ env.WS }}
        shell: bash
        run: |
          set -eo pipefail
          set +u
          source /opt/ros/humble/setup.sh
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
          colcon test-result --verbose || true
