name: auto-compile

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ROS_META_PKG: ros-humble-ros-base
      WS: robot_ws

    steps:
      - name: Checkout A.R.M repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.WS }}/src/arm
          submodules: "recursive"

      - name: clone dep repos
        working-directory: ${{ env.WS }}/src/arm
        run: |
          set -eux
          bash clone.sh

      - name: manual dep install
        run: sudo apt-get update && sudo apt-get install -y nlohmann-json3-dev

      - name: Install ROS 2 Humble APT repo and core tools
        run: |
          set -eux

          sudo apt-get update
          sudo apt-get install -y locales curl gnupg lsb-release software-properties-common

          # Locale (ROS recommends UTF-8)
          sudo locale-gen en_US en_US.UTF-8
          sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          export LANG=en_US.UTF-8

          # Universe repo (commonly needed)
          sudo add-apt-repository -y universe

          # ROS 2 apt source
          sudo mkdir -p /etc/apt/keyrings
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | \
            sudo gpg --dearmor -o /etc/apt/keyrings/ros-archive-keyring.gpg

          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/ros-archive-keyring.gpg] \
          http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | \
          sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

          sudo apt-get update
          # Choose desktop or ros-base via ROS_META_PKG env
          sudo apt-get install -y ${ROS_META_PKG} \
            python3-colcon-common-extensions python3-rosdep python3-vcstool \
            build-essential cmake git

      - name: Initialize rosdep
        run: |
          set -eux
          sudo rosdep init || true
          rosdep update

      - name: Install system dependencies for all packages (rosdep)
        working-directory: ${{ env.WS }}
        run: |
          set -eux
          # Install system deps for all packages in src/, ignoring source packages themselves
          rosdep install --from-paths src --rosdistro humble --skip-keys "" --ignore-src -y

      - name: Build with colcon (Release)
        working-directory: ${{ env.WS }}
        shell: bash
        run: |
          set -eo pipefail
          set +u
          source /opt/ros/humble/setup.sh
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
          colcon test-result --verbose || true
